- Admin:
    - Admin Console:
        - abbr: AD
          href: https://admin.21bristoe.com
    - Stats:
        - abbr: ST
          href: https://stats.21bristoe.com
    - Drink Hub:
        - abbr: DH
          href: https://drink-hub.21bristoe.com
